### ISSUE TITLE
Multiple response answer for question?

### ISSUE THREAD

**Issue by vinodjoshi** [amk221/train-up#1]
Is there possible to create Question Type as Multiple Response.

Right now it is good for multiple choice. How to make this feasible with checkbox so user can select more than one answer.

**Comment by amk221** [comment]
It is possible to make custom question types. See the [orderable](https://github.com/amk221/train-up.orderable_questions) question type for an example.

**Comment by vinodjoshi** [comment]
Thanks for your reply. But i have already checked "orderable" question type.  It is not as per my need.
Let me explain more :
There are four option for any question and two of them are correct. 
See the screenshot for more details : http://prntscr.com/6r4ulx

Hope you got my problem. I am trying to create new add-on for train up. Give me a way how can i create it?

**Comment by amk221** [comment]
I was suggesting you make your own, using the plugin I linked to as a starting point :)
(I don't have time to create a multiple-selection-multiple-choice question type at the moment)

_Edit:_
I will create a new repository for a demo question type so you can work from there

**Comment by vinodjoshi** [comment]
It will be fine. I will try.
